
package dao;

import modelo.HibernateUtil;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pojo.Raiz;
import pojo.Seguimiento;




public class DaoSeguimiento {
    
     private Session sesion;
    private Transaction tx;
    
    public void save(Seguimiento seguimiento ) throws HibernateException {
  
    try{     
  
        initOperation();
        sesion.persist(seguimiento);        
        tx.commit();
        
    
    }catch(HibernateException he)
    {
        
        trueExcepcion(he); 
        throw he; 
    
    
    } finally
    {
                
        sesion.close();
    
    }
    
    

}

    private void initOperation() throws HibernateException 

    {
    
    sesion = HibernateUtil.getSessionFactory().openSession(); 
        tx = sesion.beginTransaction(); 
    
}

    private void trueExcepcion(HibernateException he) throws HibernateException 
    { 
        tx.rollback(); 
        throw new HibernateException("Ocurri√≥ un error en la capa de acceso a datos", he); 
    }
    
    
}
